name: Deploy using Github Pages

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Installing packages
        run: yarn
      - name: Building the application
        run: yarn build
      - name: Deploy to GitHub pages
        uses: akhileshns/heroku-deploy@v3.12.12
        run: |
          git config --global user.name "yashkushwaha27"
          git config --global user.email "yashkkushwaha@gmail.com"
          git remote set-url origin https://${github_token}@github.com/${repository}
          yarn deploy
        with:
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
